package ru.itis.neuroteacher.ui.theme

import androidx.compose.foundation.shape.CircleShape
import androidx.compose.foundation.shape.RoundedCornerShape
import androidx.compose.runtime.Composable
import androidx.compose.runtime.CompositionLocalProvider
import androidx.compose.runtime.Immutable
import androidx.compose.runtime.staticCompositionLocalOf
import androidx.compose.ui.graphics.Color
import androidx.compose.ui.text.TextStyle
import androidx.compose.ui.text.font.FontWeight
import androidx.compose.ui.text.style.TextAlign
import androidx.compose.ui.unit.Dp
import androidx.compose.ui.unit.TextUnit
import androidx.compose.ui.unit.dp
import androidx.compose.ui.unit.sp

@Immutable
data class AppColors(
    val primary: Color,
    val primaryVariant: Color,
    val backgroundLight: Color,
    val cardBackground: Color,
    val textPrimary: Color,
    val textSecondary: Color,
    val textHint: Color,
    val textLabel: Color,
    val borderDefault: Color,
    val borderFocused: Color,
    val borderError: Color,
    val error: Color,
    val disabled: Color,
    val backgroundGradient: List<Color>,
    val backgroundGradientMain: List<Color>,
    val iconGradientStart: Color,
    val iconGradientEnd: Color,
    val iconGradientSecondaryStart: Color,
    val iconGradientSecondaryEnd: Color,
    val shadowColor: Color,
    val bottomBarBorder: Color,
    val textOnWhite: Color,
    val successBackground: Color,
    val errorBackground: Color,
    val successBorder: Color,
    val chartSuccessBorder: Color,
    val chartErrorBorder: Color,
    val errorBorder: Color,
    val explanationBackground: Color,
    val explanationText: Color,
    val progressBarTrack: Color,
    val white: Color,
    val cardSubtitleColor: Color,
    val textOnCard: Color,
    val logoBackgroundColor: Color,
    val buttonUnselectedBackground: Color,
    val buttonUnselectedText: Color,
    val deleteIconColor: Color,
    val profileTextPrimary: Color,
    val iconBookStroke: Color,
    val iconArrowStroke: Color,
    val iconTrophyStroke: Color,
    val iconCheckStroke: Color,
    val cameraButtonBackground: Color,
    val cameraBackButtonBackground: Color,
    val cameraButtonShadow: Color,
    val photoDemoQuestionCardBackground: Color,

    val photoDemoBgBlack: Color,
    val photoDemoPhotoGray: Color,
    val photoDemoTextDark: Color,
    val photoDemoTextSecondary: Color,
    val photoDemoCardBg: Color,
    val photoDemoButtonBgUnselected: Color,
    val photoDemoGradientStart: Color,
    val photoDemoGradientEnd: Color,
    val historyBgGradientStart: Color,
    val historyBgGradientMid: Color,
    val historyBgGradientEnd: Color,
    val statusSuccess: Color,
    val statusError: Color,
    val recentTestTitleColor: Color,
    val recentTestDateColor: Color,
    val recentTestScoreColor: Color,
    val viewAllButtonColor: Color,
    val bottomBarSelectedColor: Color,
    val bottomBarUnselectedColor: Color,
    val emptyStateIconBg: Color,
    val emptyStateSubtitleColor: Color,
    val emptyStateButtonGradientStart: Color,
    val emptyStateButtonGradientEnd: Color,
    val authLinkColor: Color,
    val avatarGradientStart: Color,
    val avatarGradientEnd: Color,
)

@Immutable
data class AppTypography(
    val title: TextStyle,
    val subtitle: TextStyle,
    val button: TextStyle,
    val label: TextStyle,
    val placeholder: TextStyle,
    val error: TextStyle,
    val welcomeText: TextStyle,
    val cardTitle: TextStyle,
    val cardSubtitle: TextStyle,
    val sectionTitle: TextStyle,
    val emptyStateText: TextStyle,
    val profileTitle: TextStyle,
    val historyEmptyStateTitle: TextStyle,
    val historyEmptyStateSubtitle: TextStyle,
    val authLinkStyle: TextStyle,
)

@Immutable
data class AppShapes(
    val inputCorner: RoundedCornerShape,
    val buttonCorner: RoundedCornerShape,
    val cardCorner: RoundedCornerShape,
    val iconRound: RoundedCornerShape,
    val buttonCornerSmall: RoundedCornerShape,

    val photoCardShape: RoundedCornerShape,
    val photoButtonShape: RoundedCornerShape,
    val photoQuestionButtonShape: RoundedCornerShape,
    val photoImageShape: RoundedCornerShape,
)

@Immutable
data class AppDimensions(
    val spacingXxxs: Dp,
    val spacingXs: Dp,
    val spacingSm: Dp,
    val spacingMd: Dp,
    val spacingLg: Dp,
    val spacingXl: Dp,

    val buttonHeight: Dp,
    val progressHeight: Dp,
    val textFieldMinHeight: Dp,
    val questionButtonWidth: Dp,
    val questionButtonHeight: Dp,

    val iconSizeSmall: Dp,
    val iconSizeMedium: Dp,
    val iconSize: Dp,
    val iconEmptySize: Dp,
    val iconSizeDefault: Dp,
    val iconSizeLarge: Dp,

    val headerHeight: Dp,
    val containerWidth: Dp,
    val containerCameraHeight: Dp,
    val containerTextHeight: Dp,
    val emptyStateHeight: Dp,
    val shadowElevation: Dp,
    val cardPadding: Dp,
    val paddingHorizontal: Dp,
    val logoContainerSize: Dp,
    val logoSize: Dp,

    val borderThickness: Dp,

    val fontSizeHelper: TextUnit,
    val fontSizeButton: TextUnit,
    val fontSizeCardTitle: TextUnit,
    val fontSizeTopBarTitle: TextUnit,
    val fontSizeQuestionText: TextUnit,
    val fontSizeOptionText: TextUnit,
    val fontSizeExplanationTitle: TextUnit,
    val fontSizeExplanationText: TextUnit,
    val fontSizeTopBarTitleTest: TextUnit,

    val buttonCornerRadius: Dp,
    val buttonLargeHeight: Dp,
    val buttonShadowElevation: Dp,
    val iconSizeResult: Dp,
    val fontSizeProfileSectionTitle: TextUnit,
    val fontSizeProfileButtonLabel: TextUnit,
    val cornerRadiusProfileButton: Dp,
    val borderWidthProfileButton: Dp,
    val iconSizeProfileButton: Dp,
    val spacingIconText: Dp,
    val profileHeaderHeight: Dp,
    val profileIconSize: Dp,
    val profileIconInnerSize: Dp,
    val statsCardHeightSmall: Dp,
    val statsCardHeightLarge: Dp,
    val themeButtonHeight: Dp,
    val themeButtonWidth: Dp,
    val langButtonHeight: Dp,
    val actionItemHeight: Dp,
    val profileHeaderBottomPadding: Dp,
    val profileCardTopPadding: Dp,
    val statsRowSpacing: Dp,
    val statsCardShadowElevation: Dp,
    val statsCardIconSpacing: Dp,
    val statsCardIconSize: Dp,
    val fontSizeStatsTitle: TextUnit,
    val fontSizeStatsValue: TextUnit,
    val fontSizeProfileHeaderTitle: TextUnit,
    val iconSizeThemeButton: Dp,
    val themeButtonShadowElevation: Dp,
    val spacingThemeButtonVerticalPadding: Dp,
    val spacingThemeButtonGap: Dp,
    val spacingCardHorizontalPadding: Dp,
    val dividerThickness: Dp,

    val cameraButtonSize: Dp,
    val cameraIconSize: Dp,
    val cameraBackButtonSize: Dp,
    val cameraBackIconSize: Dp,
    val cameraBottomPaddingStart: Dp,
    val cameraBottomPaddingEnd: Dp,
    val cameraTopPaddingStart: Dp,
    val cameraButtonsGap: Dp,

    val cameraOffsetX: Dp,
    val cameraButtonSizeDelta: Dp,
    val cameraIconSizeDelta: Dp,

    val photoHeight: Dp,
    val fontSizePhotoTitle: TextUnit,
    val fontSizePhotoSubtitle: TextUnit,
    val fontSizeLabel: TextUnit,
    val fontSizeButtonText: TextUnit,
    val strokeWidthSmall: Dp,
    val photoCardCorner: Dp,
    val photoButtonCorner: Dp,
    val photoQuestionButtonCorner: Dp,
    val photoQuestionButtonHeight: Dp,
    val photoMainButtonHeight: Dp,
    val photoButtonsSpacing: Dp,
    val photoCardPadding: Dp,
    val historyHeaderHeight: Dp,
    val historySearchHeight: Dp,
    val historyItemCardHeight: Dp,
    val historyItemCornerRadius: Dp,
    val historySearchCornerRadius: Dp,
    val historyStatusDotSize: Dp,
    val recentTestCardHeight: Dp,
    val recentTestCardCornerRadius: Dp,
    val recentTestTitleFontSize: TextUnit,
    val recentTestDateFontSize: TextUnit,
    val recentTestScoreFontSize: TextUnit,
    val viewAllButtonFontSize: TextUnit,
    val recentTestStatusDotSize: Dp,
    val bottomBarHeight: Dp,
    val bottomBarIconContainerSize: Dp,
    val bottomBarIconSize: Dp,
    val bottomBarTextSize: TextUnit,
    val bottomBarIconTextGap: Dp,
    val bottomBarVerticalPadding: Dp,
    val historyEmptyStateHeight: Dp,
    val historyEmptyStateCornerRadius: Dp,
    val historyEmptyStateIconCircleSize: Dp,
    val historyEmptyStateIconSize: Dp,
    val historyEmptyStateButtonWidth: Dp,
    val historyEmptyStateButtonHeight: Dp,
    val historyEmptyStateButtonCornerRadius: Dp,

    )

val LocalAppDimensions = staticCompositionLocalOf {
    AppDimensions(
        spacingXxxs = 4.dp, spacingXs = 8.dp, spacingSm = 12.dp,
        spacingMd = 16.dp, spacingLg = 24.dp, spacingXl = 32.dp,

        buttonHeight = 50.dp, progressHeight = 4.dp, textFieldMinHeight = 300.dp,
        questionButtonWidth = 64.dp, questionButtonHeight = 48.dp,

        iconSizeSmall = 20.dp, iconSizeMedium = 24.dp,
        iconSize = 80.dp, iconEmptySize = 96.dp,
        iconSizeDefault = 40.dp, iconSizeLarge = 48.dp,

        headerHeight = 96.dp, containerWidth = 345.dp,
        containerCameraHeight = 236.dp, containerTextHeight = 216.dp,
        emptyStateHeight = 200.dp, shadowElevation = 8.dp,
        cardPadding = 32.dp, paddingHorizontal = 24.dp,
        logoContainerSize = 80.dp, logoSize = 60.dp,

        borderThickness = 1.5.dp,

        fontSizeHelper = 12.sp, fontSizeButton = 16.sp,
        fontSizeCardTitle = 16.sp, fontSizeTopBarTitle = 20.sp,
        fontSizeQuestionText = 17.sp, fontSizeOptionText = 15.sp,
        fontSizeExplanationTitle = 14.sp, fontSizeExplanationText = 13.sp,
        fontSizeTopBarTitleTest = 18.sp,

        buttonCornerRadius = 14.dp,
        buttonLargeHeight = 80.dp,
        buttonShadowElevation = 4.dp,
        iconSizeResult = 20.dp,
        fontSizeProfileSectionTitle = 18.sp,
        fontSizeProfileButtonLabel = 14.sp,
        cornerRadiusProfileButton = 14.dp,
        borderWidthProfileButton = 1.dp,
        iconSizeProfileButton = 16.dp,
        spacingIconText = 8.dp,
        profileHeaderHeight = 128.dp,
        profileIconSize = 80.dp,
        profileIconInnerSize = 40.dp,
        statsCardHeightSmall = 92.dp,
        statsCardHeightLarge = 112.dp,
        themeButtonHeight = 72.dp,
        themeButtonWidth = 90.dp,
        langButtonHeight = 44.dp,
        actionItemHeight = 56.dp,
        profileHeaderBottomPadding = 24.dp,
        profileCardTopPadding = 20.dp,
        statsRowSpacing = 12.dp,
        statsCardShadowElevation = 4.dp,
        statsCardIconSpacing = 4.dp,
        statsCardIconSize = 19.dp,
        fontSizeStatsTitle = 14.sp,
        fontSizeStatsValue = 24.sp,
        fontSizeProfileHeaderTitle = 24.sp,
        iconSizeThemeButton = 20.dp,
        themeButtonShadowElevation = 4.dp,
        spacingThemeButtonVerticalPadding = 8.dp,
        spacingThemeButtonGap = 4.dp,
        spacingCardHorizontalPadding = 8.dp,
        dividerThickness = 1.dp,

        cameraButtonSize = 68.dp,
        cameraIconSize = 28.dp,
        cameraBackButtonSize = 40.dp,
        cameraBackIconSize = 24.dp,
        cameraBottomPaddingStart = 121.5.dp,
        cameraBottomPaddingEnd = 213.5.dp,
        cameraTopPaddingStart = 16.dp,
        cameraButtonsGap = 32.dp,

        cameraOffsetX = (-40).dp,
        cameraButtonSizeDelta = 12.dp,
        cameraIconSizeDelta = 4.dp,

        photoHeight = 340.dp,
        fontSizePhotoTitle = 18.sp,
        fontSizePhotoSubtitle = 14.sp,
        fontSizeLabel = 14.sp,
        fontSizeButtonText = 16.sp,
        strokeWidthSmall = 2.dp,
        photoCardCorner = 16.dp,
        photoButtonCorner = 16.dp,
        photoQuestionButtonCorner = 14.dp,
        photoQuestionButtonHeight = 48.dp,
        photoMainButtonHeight = 56.dp,
        photoButtonsSpacing = 8.dp,
        photoCardPadding = 24.dp,
        historyHeaderHeight = 75.dp,
        historySearchHeight = 50.dp,
        historyItemCardHeight = 110.dp,
        historyItemCornerRadius = 16.dp,
        historySearchCornerRadius = 14.dp,
        historyStatusDotSize = 12.dp,
        recentTestCardHeight = 111.dp,
        recentTestCardCornerRadius = 16.dp,
        recentTestTitleFontSize = 18.sp,
        recentTestDateFontSize = 14.sp,
        recentTestScoreFontSize = 14.sp,
        viewAllButtonFontSize = 14.sp,
        recentTestStatusDotSize = 12.dp,
        bottomBarHeight = 81.dp,
        bottomBarIconContainerSize = 24.dp,
        bottomBarIconSize = 20.dp,
        bottomBarTextSize = 12.sp,
        bottomBarIconTextGap = 4.dp,
        bottomBarVerticalPadding = 8.dp,
        historyEmptyStateHeight = 364.dp,
        historyEmptyStateCornerRadius = 24.dp,
        historyEmptyStateIconCircleSize = 96.dp,
        historyEmptyStateIconSize = 40.dp,
        historyEmptyStateButtonWidth = 137.dp,
        historyEmptyStateButtonHeight = 48.dp,
        historyEmptyStateButtonCornerRadius = 14.dp,
        )
}

val LocalAppColors = staticCompositionLocalOf {
    AppColors(
        primary = Color.Unspecified,
        primaryVariant = Color.Unspecified,
        backgroundLight = Color.Unspecified,
        cardBackground = Color.Unspecified,
        textPrimary = Color.Unspecified,
        textSecondary = Color.Unspecified,
        textHint = Color.Unspecified,
        textLabel = Color.Unspecified,
        borderDefault = Color.Unspecified,
        borderFocused = Color.Unspecified,
        borderError = Color.Unspecified,
        error = Color.Unspecified,
        disabled = Color.Unspecified,
        backgroundGradient = emptyList(),
        backgroundGradientMain = emptyList(),
        iconGradientStart = Color.Unspecified,
        iconGradientEnd = Color.Unspecified,
        iconGradientSecondaryStart = Color.Unspecified,
        iconGradientSecondaryEnd = Color.Unspecified,
        shadowColor = Color.Unspecified,
        bottomBarBorder = Color.Unspecified,
        textOnWhite = Color.Unspecified,
        successBackground = Color.Unspecified,
        errorBackground = Color.Unspecified,
        successBorder = Color.Unspecified,
        chartSuccessBorder = Color.Unspecified,
        errorBorder = Color.Unspecified,
        chartErrorBorder = Color.Unspecified,
        explanationBackground = Color.Unspecified,
        explanationText = Color.Unspecified,
        progressBarTrack = Color.Unspecified,
        white = Color.Unspecified,
        cardSubtitleColor = Color.Unspecified,
        textOnCard = Color.Unspecified,
        logoBackgroundColor = Color.Unspecified,
        buttonUnselectedBackground = Color.Unspecified,
        buttonUnselectedText = Color.Unspecified,
        deleteIconColor = Color.Unspecified,
        profileTextPrimary = Color.Unspecified,
        iconBookStroke = Color.Unspecified,
        iconArrowStroke = Color.Unspecified,
        iconTrophyStroke = Color.Unspecified,
        iconCheckStroke = Color.Unspecified,
        cameraButtonBackground = Color.Unspecified,
        cameraBackButtonBackground = Color.Unspecified,
        cameraButtonShadow = Color.Unspecified,
        photoDemoQuestionCardBackground = Color.Unspecified,

        photoDemoBgBlack = Color.Unspecified,
        photoDemoPhotoGray = Color.Unspecified,
        photoDemoTextDark = Color.Unspecified,
        photoDemoTextSecondary = Color.Unspecified,
        photoDemoCardBg = Color.Unspecified,
        photoDemoButtonBgUnselected = Color.Unspecified,
        photoDemoGradientStart = Color.Unspecified,
        photoDemoGradientEnd = Color.Unspecified,
        historyBgGradientStart = Color.Unspecified,
        historyBgGradientMid = Color.Unspecified,
        historyBgGradientEnd = Color.Unspecified,
        statusSuccess = Color.Unspecified,
        statusError = Color.Unspecified,
        recentTestTitleColor = RecentTestTitleColor,
        recentTestDateColor = RecentTestDateColor,
        recentTestScoreColor = RecentTestScoreColor,
        viewAllButtonColor = ViewAllButtonColor,
        bottomBarSelectedColor = BottomBarSelectedColor,
        bottomBarUnselectedColor = BottomBarUnselectedColor,
        emptyStateIconBg = EmptyStateIconBg,
        emptyStateSubtitleColor = EmptyStateSubtitleColor,
        emptyStateButtonGradientStart = EmptyStateButtonGradientStart,
        emptyStateButtonGradientEnd = EmptyStateButtonGradientEnd,
        authLinkColor = AuthLinkColor,
        avatarGradientStart = Color.Unspecified,
        avatarGradientEnd = Color.Unspecified,
    )
}

val LocalAppTypography = staticCompositionLocalOf {
    AppTypography(
        title = TextStyle.Default,
        subtitle = TextStyle.Default,
        button = TextStyle.Default,
        label = TextStyle.Default,
        placeholder = TextStyle.Default,
        error = TextStyle.Default,
        welcomeText = TextStyle.Default,
        cardTitle = TextStyle.Default,
        cardSubtitle = TextStyle.Default,
        sectionTitle = TextStyle.Default,
        emptyStateText = TextStyle.Default,
        profileTitle = TextStyle.Default,
        historyEmptyStateTitle = TextStyle.Default,
        historyEmptyStateSubtitle = TextStyle.Default,
        authLinkStyle = TextStyle.Default,
    )
}

val LocalAppShapes = staticCompositionLocalOf {
    AppShapes(
        inputCorner = RoundedCornerShape(12.dp),
        buttonCorner = RoundedCornerShape(12.dp),
        cardCorner = RoundedCornerShape(24.dp),
        iconRound = CircleShape,
        buttonCornerSmall = RoundedCornerShape(14.dp),

        photoCardShape = RoundedCornerShape(16.dp),
        photoButtonShape = RoundedCornerShape(16.dp),
        photoQuestionButtonShape = RoundedCornerShape(14.dp),
        photoImageShape = RoundedCornerShape(24.dp),
    )
}

@Composable
fun AppTheme(
    darkTheme: Boolean = false,
    content: @Composable () -> Unit
) {
    val colors = if (darkTheme) {
        AppColors(
            primary = PrimaryDark,
            primaryVariant = PrimaryVariantDark,
            backgroundLight = BackgroundLightDark,
            cardBackground = CardBackgroundDark,
            textPrimary = TextPrimaryDark,
            textSecondary = TextSecondaryDark,
            textHint = TextHintDark,
            textLabel = TextLabelDark,
            borderDefault = BorderDefaultDark,
            borderFocused = BorderFocusedDark,
            borderError = BorderErrorDark,
            error = ErrorDark,
            disabled = DisabledDark,
            backgroundGradient = BackgroundGradientDark,
            backgroundGradientMain = BackgroundGradientMainDark,
            iconGradientStart = IconGradientStart,
            iconGradientEnd = IconGradientEnd,
            iconGradientSecondaryStart = IconGradientSecondaryStart,
            iconGradientSecondaryEnd = IconGradientSecondaryEnd,
            shadowColor = ShadowColorDark,
            bottomBarBorder = BottomBarBorderDark,
            textOnWhite = TextOnWhiteDark,
            successBackground = SuccessBackgroundDark,
            errorBackground = ErrorBackgroundDark,
            successBorder = SuccessBorderDark,
            chartSuccessBorder = ChartSuccessBorderDark,
            chartErrorBorder = ChartErrorBorderDark,
            errorBorder = ErrorBorderDark,
            explanationBackground = ExplanationBackgroundDark,
            explanationText = ExplanationTextDark,
            progressBarTrack = ProgressBarTrackDark,
            white = Color.White,
            cardSubtitleColor =  BottomBarUnselectedColor,
            textOnCard = TextPrimaryDark,
            logoBackgroundColor = LogoBackgroundColorDark,
            buttonUnselectedBackground = ButtonUnselectedBackgroundDark,
            buttonUnselectedText = ButtonUnselectedTextDark,
            deleteIconColor = DeleteIconColorDark,
            profileTextPrimary = ProfileTextPrimaryDark,
            iconBookStroke = IconBookStrokeDark,
            iconArrowStroke = IconArrowStrokeDark,
            iconTrophyStroke = IconTrophyStrokeDark,
            iconCheckStroke = IconCheckStrokeDark,
            cameraButtonBackground = CameraButtonBackgroundDark,
            cameraBackButtonBackground = CameraBackButtonBackgroundDark,
            cameraButtonShadow = CameraButtonShadowDark,
            photoDemoQuestionCardBackground = PhotoDemoQuestionCardBackgroundDark,

            photoDemoBgBlack = PhotoDemoBgBlackDark,
            photoDemoPhotoGray = PhotoDemoPhotoGrayDark,
            photoDemoTextDark = PhotoDemoTextDarkDark,
            photoDemoTextSecondary = PhotoDemoTextSecondaryDark,
            photoDemoCardBg = PhotoDemoCardBgDark,
            photoDemoButtonBgUnselected = PhotoDemoButtonBgUnselectedDark,
            photoDemoGradientStart = PhotoDemoGradientStartDark,
            photoDemoGradientEnd = PhotoDemoGradientEndDark,
            historyBgGradientStart = TextOnWhite,
            historyBgGradientMid = CardBackgroundDark,
            historyBgGradientEnd = TextOnWhite,
            statusSuccess = StatusSuccessColor,
            statusError = StatusErrorColor,
            recentTestTitleColor = Color.White,
            recentTestDateColor = BottomBarUnselectedColor,
            recentTestScoreColor = Color.White,
            viewAllButtonColor = ViewAllButtonColor,
            bottomBarSelectedColor = BottomBarSelectedColor,
            bottomBarUnselectedColor = BottomBarUnselectedColor,
            emptyStateIconBg = EmptyStateIconBg,
            emptyStateSubtitleColor = EmptyStateSubtitleColor,
            emptyStateButtonGradientStart = EmptyStateButtonGradientStart,
            emptyStateButtonGradientEnd = EmptyStateButtonGradientEnd,
            authLinkColor = AuthLinkColor,
            avatarGradientStart = AvatarGradientStartDark,
            avatarGradientEnd = AvatarGradientEndDark,
        )
    } else {
        AppColors(
            primary = Primary,
            primaryVariant = PrimaryVariant,
            backgroundLight = BackgroundLight,
            cardBackground = CardBackground,
            textPrimary = TextPrimary,
            textSecondary = TextSecondary,
            textHint = TextHint,
            textLabel = TextLabel,
            borderDefault = BorderDefault,
            borderFocused = BorderFocused,
            borderError = BorderError,
            error = Error,
            disabled = Disabled,
            backgroundGradient = BackgroundGradient,
            backgroundGradientMain = BackgroundGradientMain,
            iconGradientStart = IconGradientStart,
            iconGradientEnd = IconGradientEnd,
            iconGradientSecondaryStart = IconGradientSecondaryStart,
            iconGradientSecondaryEnd = IconGradientSecondaryEnd,
            shadowColor = ShadowColor,
            bottomBarBorder = BottomBarBorder,
            textOnWhite = TextOnWhite,
            successBackground = SuccessBackground,
            errorBackground = ErrorBackground,
            successBorder = SuccessBorder,
            chartSuccessBorder = ChartSuccessBorder,
            chartErrorBorder = ChartErrorBorder,
            errorBorder = ErrorBorder,
            explanationBackground = ExplanationBackground,
            explanationText = ExplanationText,
            progressBarTrack = ProgressBarTrack,
            white = Color.White,
            cardSubtitleColor = Color(0xFF4A5565),
            textOnCard = Color(0xFF101828),
            logoBackgroundColor = LogoBackgroundColor,
            buttonUnselectedBackground = ButtonUnselectedBackground,
            buttonUnselectedText = ButtonUnselectedText,
            deleteIconColor = DeleteIconColor,
            profileTextPrimary = ProfileTextPrimary,
            iconBookStroke = IconBookStroke,
            iconArrowStroke = IconArrowStroke,
            iconTrophyStroke = IconTrophyStroke,
            iconCheckStroke = IconCheckStroke,
            cameraButtonBackground = CameraButtonBackground,
            cameraBackButtonBackground = CameraBackButtonBackground,
            cameraButtonShadow = CameraButtonShadow,
            photoDemoQuestionCardBackground = PhotoDemoQuestionCardBackground,

            photoDemoBgBlack = PhotoDemoBgBlack,
            photoDemoPhotoGray = PhotoDemoPhotoGray,
            photoDemoTextDark = PhotoDemoTextDark,
            photoDemoTextSecondary = PhotoDemoTextSecondary,
            photoDemoCardBg = PhotoDemoCardBg,
            photoDemoButtonBgUnselected = PhotoDemoButtonBgUnselected,
            photoDemoGradientStart = PhotoDemoGradientStart,
            photoDemoGradientEnd = PhotoDemoGradientEnd,
            historyBgGradientStart = HistoryBackgroundGradientStart,
            historyBgGradientMid = HistoryBackgroundGradientMid,
            historyBgGradientEnd = HistoryBackgroundGradientEnd,
            statusSuccess = StatusSuccessColor,
            statusError = StatusErrorColor,
            recentTestTitleColor = RecentTestTitleColor,
            recentTestDateColor = RecentTestDateColor,
            recentTestScoreColor = RecentTestScoreColor,
            viewAllButtonColor = ViewAllButtonColor,
            bottomBarSelectedColor = BottomBarSelectedColor,
            bottomBarUnselectedColor = BottomBarUnselectedColor,
            emptyStateIconBg = EmptyStateIconBg,
            emptyStateSubtitleColor = EmptyStateSubtitleColor,
            emptyStateButtonGradientStart = EmptyStateButtonGradientStart,
            emptyStateButtonGradientEnd = EmptyStateButtonGradientEnd,
            authLinkColor = AuthLinkColor,
            avatarGradientStart = IconGradientStart,
            avatarGradientEnd = IconGradientEnd
        )
    }

    val typography = AppTypography(
        title = TextStyle(fontSize = 30.sp, fontWeight = FontWeight.Medium, color = colors.textPrimary),
        subtitle = TextStyle(fontSize = 14.sp, fontWeight = FontWeight.Normal, color = colors.textSecondary),
        button = TextStyle(fontSize = 16.sp, fontWeight = FontWeight.Medium, color = Color.White),
        label = TextStyle(fontSize = 14.sp, fontWeight = FontWeight.Normal, color = colors.textLabel),
        placeholder = TextStyle(fontSize = 14.sp, fontWeight = FontWeight.Normal, color = colors.textHint),
        error = TextStyle(fontSize = 12.sp, fontWeight = FontWeight.Normal, color = colors.error),
        welcomeText = TextStyle(fontSize = 24.sp, fontWeight = FontWeight.SemiBold, color = Color.White),
        cardTitle = TextStyle(fontSize = 16.sp, fontWeight = FontWeight.Medium, color = colors.textOnWhite),
        cardSubtitle = TextStyle(fontSize = 14.sp, fontWeight = FontWeight.Medium, color = colors.cardSubtitleColor),
        sectionTitle = TextStyle(fontSize = 20.sp, fontWeight = FontWeight.SemiBold, color = Color.White),
        emptyStateText = TextStyle(fontSize = 18.sp, fontWeight = FontWeight.Medium, color = colors.textOnWhite),
        profileTitle = TextStyle(fontSize = 24.sp, fontWeight = FontWeight.SemiBold, lineHeight = 32.sp, letterSpacing = 0.07.sp, color = colors.white),
        historyEmptyStateTitle = TextStyle(fontSize = 20.sp, fontWeight = FontWeight.SemiBold, lineHeight = 28.sp, letterSpacing = (-0.45).sp, color = colors.textOnCard),
        historyEmptyStateSubtitle = TextStyle(fontSize = 16.sp, fontWeight = FontWeight.Normal, lineHeight = 24.sp, letterSpacing = (-0.31).sp, color = colors.emptyStateSubtitleColor),
        authLinkStyle = TextStyle(fontSize = 16.sp, fontWeight = FontWeight.Normal, lineHeight = 24.sp, letterSpacing = 0.sp, textAlign = TextAlign.Center, color = colors.authLinkColor)
        )

    val shapes = AppShapes(
        inputCorner = RoundedCornerShape(12.dp),
        buttonCorner = RoundedCornerShape(12.dp),
        cardCorner = RoundedCornerShape(24.dp),
        iconRound = CircleShape,
        buttonCornerSmall = RoundedCornerShape(14.dp),

        photoCardShape = RoundedCornerShape(16.dp),
        photoButtonShape = RoundedCornerShape(16.dp),
        photoQuestionButtonShape = RoundedCornerShape(14.dp),
        photoImageShape = RoundedCornerShape(24.dp),
    )

    val dimensions = LocalAppDimensions.current

    CompositionLocalProvider(
        LocalAppColors provides colors,
        LocalAppTypography provides typography,
        LocalAppShapes provides shapes,
        LocalAppDimensions provides dimensions
    ) {
        content()
    }
}

object AppTheme {
    val colors: AppColors
        @Composable get() = LocalAppColors.current

    val typography: AppTypography
        @Composable get() = LocalAppTypography.current

    val shapes: AppShapes
        @Composable get() = LocalAppShapes.current

    val dimensions: AppDimensions
        @Composable get() = LocalAppDimensions.current
}